robots:
  - robot_name: euclid
    type: robot_executor
    robot_type: spot
    body_frame: euclid/body
  - robot_name: hamilton
    type: robot_executor
    robot_type: spot
    body_frame: hamilton/body
  - robot_name: apollo
    type: robot_executor
    robot_type: spot
    body_frame: apollo/body
  - robot_name: hilbert
    type: robot_executor
    robot_type: simulated-spot
    body_frame: hilbert/body
  - robot_name: samoyed
    type: phoenix
    robot_type: husky
    body_frame: samoyed/base_link
  - robot_name: gauss
    type: phoenix
    robot_type: husky
    body_frame: gauss/base_link
planners:
  goto_points:
    plugin:
      type: GotoPoints
  hybrid_language_planner:
    plugin:
      type: HybridLanguagePlanner
      domain_type: Pddl
      pddl_domain_name: GotoObjectDomain
      llm_config: ${ADT4_DLS_PKG}/config/${config}/llm_config.yaml
      dcg_config: ${ADT4_DLS_PKG}/config/${config}/dcg_config.yaml
  language_planner:
    plugin:
      type: LanguagePlanner
      domain_type: Pddl
      #pddl_domain_name: RegionObjectRearrangementDomain
      pddl_domain_name: GotoObjectDomain
      llm_config: ${ADT4_DLS_PKG}/config/${config}/llm_config.yaml
  tsp_planner:
    plugin:
      type: Tsp
      solver: 2opt
  visit_objects_pddl:
    plugin:
      type: Pddl
      domain_name: GotoObjectDomain
  rearrange_objects_pddl:
    plugin:
      type: Pddl
      domain_name: ObjectRearrangementDomain
  region_rearrange_objects_pddl:
    plugin:
      type: Pddl
      domain_name: RegionObjectRearrangementDomain
